version: "3"

services:
  influxdb:
    image: influxdb:2.1.1
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086

  telegraf:
    image: telegraf:1.19
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
    env_file:
      - .env
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana-oss:8.4.3
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:3000
  
  mosquitto:
    image: eclipse-mosquitto:1.6.12
    container_name: mosquitto
    volumes:
      - ${MOSQUITTO_CFG_PATH}:/etc/mosquitto/config/mosquitto.conf:rw
    ports:
      - 1883:1883  
      - 9001:9001

volumes:
  grafana-storage:
  influxdb-storage:

