version: "3"

services:
  influxdb:
    image: influxdb:2.1.1
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086

  telegraf:
    image: telegraf:1.19
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
    env_file:
      - .env
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana-oss:8.4.3
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:3000
  
  mosquitto:
    image: eclipse-mosquitto:1.6.12
    container_name: mosquitto
    volumes:
      - ${MOSQUITTO_CFG_PATH}:/etc/mosquitto/config/mosquitto.conf:rw
    ports:
      - 1883:1883  
      - 9001:9001

  # zigbee2mqtt:
  #   container_name: zigbee2mqtt
  #   image: koenkk/zigbee2mqtt
  #   restart: unless-stopped
  #   volumes:
  #     - ./data:/app/data
  #     - /run/udev:/run/udev:ro
  #   ports:
  #     # Frontend port
  #     - 8080:8080
  #   environment:
  #     - TZ=America/Indianapolis
  #   devices:
  #     # Make sure this matched your adapter location
  #     - USB\VID_10C4&PID_EA60\5807B95F6245ED1188D2C88F0A86E0B4
  #     #/dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0018ED3DDF-if00:/dev/ttyACM0

volumes:
  grafana-storage:
  influxdb-storage:

